---
# Install elasticsearch packages

- name: unwanted packages are removed
  package:
    name: "{{ elasticsearch_packages_remove }}"
    state: absent
  become: true
  when: elasticsearch_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ elasticsearch_packages_repos }}"
    state: "{{ elasticsearch_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ elasticsearch_packages_prereq }}"
    state: "{{ elasticsearch_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ elasticsearch_packages_install }}"
    state: "{{ elasticsearch_packages_state }}"
  become: true
