---
# Template configuration files for elasticsearch

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ elasticsearch_templates_copy }}"
  when: elasticsearch_copy_templates
